---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004

# Install python-pip
addons:
  apt:
    packages:
      - python-pip

install:
  # Install molecule
  - pip install ansible ansible-lint docker flake8 molecule testinfra yamllint

  # Check molecule version
  - molecule --version

  # Check ansible version
  - ansible --version

script:
  # Run tests
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
