---
- name: Install dnsmasq
  yum:
    name: "{{ dnsmasq_install_pkg }}"
    state: "{{ dnsmasq_install_state }}"
  register: dnsmasq_install_retries_reg
  retries: "{{ dnsmasq_install_retries }}"
  until: dnsmasq_install_retries_reg is success

- name: Copy dnsmasq config
  template:
    src: "{{ dnsmasq_conf_template }}"
    dest: "{{ dnsmasq_conf_file }}"
    mode: "{{ dnsmasq_conf_file_mode }}"
  notify: "{{ dnsmasq_notify_restart }}"
  when: dnsmasq_server is defined

- name: Copy dnsmasq consul domain config
  template:
    src: "{{ dnsmasq_conf_template_file }}"
    dest: "{{ dnsmasq_conf_consul_file }}"
    mode: "{{ dnsmasq_conf_consul_file_mode }}"
  notify: "{{ dnsmasq_notify_restart }}"

- name: Run dnsmasq related handler
  meta: flush_handlers

- name: Ensure dnsmasq is started and enabled
  service:
    name: "{{ dnsmasq_service_name }}"
    state: "{{ dnsmasq_service_state }}"
    enabled: "{{ dnsmasq_service_enabled }}"
