---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
        molecule_distros: ['centos8', 'ubuntu1804', 'ubuntu2004']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install docker
          python3 -m pip install --upgrade pip
          # python3 -m pip install -r requirements.txt
          python3 -m pip install ansible ansible-lint docker flake8 molecule testinfra yamllint
      - name: Test with molecule
        run: |
          molecule test
